using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Ratings
{
    public class RatedTitles : IRatedTitles
    {
        List<IRatedTitle> _ratedTitles;

        public List<IRatedTitle> GetRatedTitles()
        {
            _ratedTitles = new List<IRatedTitle>
            {
                new RatedTitle { Title = " Worth It   ", Artist = "Fifth Harmony feat. Kid Ink" },
                new RatedTitle { Title = "2012 (It Aint The End)  ", Artist = "Jay Sean Feat Nicki Minaj" },
                new RatedTitle { Title = "5,6,7,8 ", Artist = "Steps" },
                new RatedTitle { Title = "7 Years (Mike D Remix) (SE) (Kutt Edit) ", Artist = "Lukas Graham" },
                new RatedTitle { Title = "Ah Yeah! (Original Mix)	", Artist = "Will Sparks" },
                new RatedTitle { Title = "All About That Bass ", Artist = "Meghan Trainor" },
                new RatedTitle { Title = "All Good (Intro Dirty)  ", Artist = "De La Sol ft Chaka Khan" },
                new RatedTitle { Title = "All I Do Is Win (Dirty)(75 Bpm) ", Artist = "DJ Khaled Feat. T-Pain, Ludacris, Snoop Dogg & Rick Ross" },
                new RatedTitle { Title = "All Summer Long ", Artist = "Kid Rock" },
                new RatedTitle { Title = "Always On Time  ", Artist = "Ja Rule feat. Ashanti" },
                new RatedTitle { Title = "American Boy (CFLO Edit - Dirty)    ", Artist = "Estelle ft Kanye West" },
                new RatedTitle { Title = "Anaconda (Explicit Edit)    ", Artist = "Nicki Minaj" },
                new RatedTitle { Title = "Angel (feat. Rayvon)    ", Artist = "Shaggy" },
                new RatedTitle { Title = "Animals ", Artist = "Martin Garrix" },
                new RatedTitle { Title = "Are You With Me ", Artist = "Lost Frequencies" },
                new RatedTitle { Title = "As Your Friend (Leroy Styles & Afrojack Extended Mix)   ", Artist = "Afrojack feat. Chris Brown" },
                new RatedTitle { Title = "Back In Black (MorganJ Bootleg) (Enrie BeeHive Edit)    ", Artist = "AC/DC" },
                new RatedTitle { Title = "Back in Time    ", Artist = "Pitbull" },
                new RatedTitle { Title = "Bad (Original Mix)  ", Artist = "David Guetta and Showtek ft. Vassy" },
                new RatedTitle { Title = "Bad Medicine (Rock Shock Remix) ", Artist = "Bon Jovi" },
                new RatedTitle { Title = "Barbra Streisand    ", Artist = "Duck Sauce" },
                new RatedTitle { Title = "Be Faithful ", Artist = "Fatman Scoop And Crooklyn Clan" },
                new RatedTitle { Title = "Beat It ", Artist = "Michael Jackson" },
                new RatedTitle { Title = "Beautiful (X-Mix)   ", Artist = "Snoop Dogg ft Pharrell & Uncle Charlie" },
                new RatedTitle { Title = "Beautiful ft. Colby O\'Donis and Kardinal Offishall	", Artist = "Akon" },
                new RatedTitle { Title = "Beautiful Girls ", Artist = "Sean Kingston" },
                new RatedTitle { Title = "Best Night  ", Artist = "Justice Crew" },
                new RatedTitle { Title = "Big Booty Bitches - Original Mix    ", Artist = "Bombs Away" },
                new RatedTitle { Title = "Bills   ", Artist = "Lunchmoney Lewis" },
                new RatedTitle { Title = "Birthday (feat. Cody Wise)  ", Artist = "will.i.am" },
                new RatedTitle { Title = "Black And Yellow    ", Artist = "Wiz Khalifa" },
                new RatedTitle { Title = "Black or White (CFLO Intro) ", Artist = "Michael Jackson" },
                new RatedTitle { Title = "Blame   ", Artist = "Calvin Harris Feat John Newman" },
                new RatedTitle { Title = "Blister In The Sun  ", Artist = "Violent Femmes" },
                new RatedTitle { Title = "Blow Me (One Last Kiss) ", Artist = "P!nk" },
                new RatedTitle { Title = "Blurred Lines   ", Artist = "Robin Thicke" },
                new RatedTitle { Title = "Bom Bom ", Artist = "Sam And The Womp" },
                new RatedTitle { Title = "Boom Boom (Funkymix by Mark Roberts)    ", Artist = "Justice Crew" },
                new RatedTitle { Title = "Boom Boom Boom  ", Artist = "Outhere Brothers" },
                new RatedTitle { Title = "Boom Boom Boom  ", Artist = "The Outhere Brothers" },
                new RatedTitle { Title = "Boom Boom Pow   ", Artist = "Black Eyed Peas" },
                new RatedTitle { Title = "Boom Clap [djmebbe.com] ", Artist = "Charli XCX" },
                new RatedTitle { Title = "Booyah (Original Mix)   ", Artist = "Showtek feat. We Are Loud & Sonny Wilson" },
                new RatedTitle { Title = "Bouncer (feat. Ookay ) [Original Mix]   ", Artist = "Showtek" },
                new RatedTitle { Title = "Brad Pitt\'s Cousin (feat. XP)	", Artist = "Macklemore & Ryan Lewis" },
                new RatedTitle { Title = "Break Free  ", Artist = "Ariana Grande" },
                new RatedTitle { Title = "Break The Rules ", Artist = "Charli XCX" },
                new RatedTitle { Title = "Break The Rules (Xmix Remix)    ", Artist = "Charli Xcx" },
                new RatedTitle { Title = "Breathe feat. Sean Paul     ", Artist = "Blu Cantrell" },
                new RatedTitle { Title = "Brown Eyed Girl ", Artist = "Van Morrison" },
                new RatedTitle { Title = "Bulletproof ", Artist = "La Roux" },
                new RatedTitle { Title = "Bust a Move ", Artist = "Young MC" },
                new RatedTitle { Title = "Buttons (feat. Snoop Dogg)  ", Artist = "Pussycat Dolls" },
                new RatedTitle { Title = "C\'mon (X-Mix)	", Artist = "Ke$ha" },
                new RatedTitle { Title = "Calabria Destination (feat.Crystal Waters)  ", Artist = "Alex Gaudino" },
                new RatedTitle { Title = "California Gurls    ", Artist = "Katy Perry f. Snoop Dogg" },
                new RatedTitle { Title = "California Love (Jason Dee Party Intro) ", Artist = "Dr Dre ft. Tupac" },
                new RatedTitle { Title = "Call Me Maybe   ", Artist = "Carly Rae Jepsen" },
                new RatedTitle { Title = "Can\'t Feel My Face	", Artist = "The Weeknd" },
                new RatedTitle { Title = "Changed The Way You Kiss Me ", Artist = "Example" },
                new RatedTitle { Title = "Cheap Thrills   ", Artist = "Sia" },
                new RatedTitle { Title = "Check It Out    ", Artist = "Will.I.Am and Nicki Minaj" },
                new RatedTitle { Title = "Cheerleader (Felix Jaehn Remix) ", Artist = "OMI" },
                new RatedTitle { Title = "Clarity (Tiesto Remix)  ", Artist = "Zedd feat. Foxes" },
                new RatedTitle { Title = "Closer (feat. Halsey)   ", Artist = "The Chainsmokers" },
                new RatedTitle { Title = "Clothes Off ", Artist = "Gym Class Heroes" },
                new RatedTitle { Title = "Commander   ", Artist = "Kelly Rowland Feat. David Guetta" },
                new RatedTitle { Title = "Cosby Sweater   ", Artist = "Hilltop Hoods" },
                new RatedTitle { Title = "Cotton Eyed Joe ", Artist = "Rednex" },
                new RatedTitle { Title = "Crazy in Love (feat. Jay-Z) ", Artist = "Beyonce" },
                new RatedTitle { Title = "Crazy Kids  ", Artist = "Ke$ha Feat Will.i.am" },
                new RatedTitle { Title = "Crazy Train ", Artist = "Ozzy Osbourne" },
                new RatedTitle { Title = "Danza Kuduro (DJ Jenil Everyday I\'m Shufflin\' Intro)    ", Artist = "Don Omar ft. Lucenzo" },
                new RatedTitle { Title = "Day N Nite - (Crookers Remix)	", Artist = "Kid Cudi" },
                new RatedTitle { Title = "Dedication To My Ex (Miss That) ", Artist = "Lloyd Feat Andre 3000 & Lil Wayne" },
                new RatedTitle { Title = "Deja Vu (feat. Jay Z)   ", Artist = "Beyonce" },
                new RatedTitle { Title = "Dirrty feat. Redman ", Artist = "Christina Aguilera" },
                new RatedTitle { Title = "Do It Again ", Artist = "Pia Mia Feat Chris Brown & Tyga" },
                new RatedTitle { Title = "Domino  ", Artist = "Jessie J" },
                new RatedTitle { Title = "Don\'t Stop the Party	", Artist = "Pitbull Feat TJR" },
                new RatedTitle { Title = "Don\'t Stop The Party	", Artist = "The Black Eyed Peas" },
                new RatedTitle { Title = "Don\'t Tell \'Em (Feat. Y.G.) ", Artist = "Jeremih" },
                new RatedTitle { Title = "Don\'t You Worry Child	", Artist = "Swedish House Mafia Feat John Martin" },
                new RatedTitle { Title = "Dont Cha (feat. Busta Rhymes)   ", Artist = "Pussycat Dolls" },
                new RatedTitle { Title = "Dont Phunk with my Heart    ", Artist = "Black Eyed Peas" },
                new RatedTitle { Title = "Downtown (Cdq)  ", Artist = "Macklemore & Ryan Lewis" },
                new RatedTitle { Title = "Drinking From The Bottle    ", Artist = "Calvin Harris Feat Tinie Tempah" },
                new RatedTitle { Title = "Drop it Like it\'s Hot	", Artist = "Snoop Dogg" },
                new RatedTitle { Title = "Dynamite    ", Artist = "Taio Cruz" },
                new RatedTitle { Title = "Eagle Rock  ", Artist = "Daddy Cool" },
                new RatedTitle { Title = "Empire State of Mind (feat. Alicia Keys)    ", Artist = "Jay-Z" },
                new RatedTitle { Title = "Family Affair   ", Artist = "Mary J. Blige" },
                new RatedTitle { Title = "Fancy   ", Artist = "Iggy Azalea" },
                new RatedTitle { Title = "Fast Car    ", Artist = "Tracy Chapman" },
                new RatedTitle { Title = "Feel So Close   ", Artist = "Calvin Harris" },
                new RatedTitle { Title = "Fergalicious    ", Artist = "Fergie" },
                new RatedTitle { Title = "Finally (DAZZ 2k15 Remix)   ", Artist = "CeCe Peniston" },
                new RatedTitle { Title = "Firework    ", Artist = "Katy Perry" },
                new RatedTitle { Title = "Five More Hours ", Artist = "Deorro & Chris Brown" },
                new RatedTitle { Title = "Five More Hours ", Artist = "Deorro X Chris Brown" },
                new RatedTitle { Title = "Flo Rida ft. Pitbull - MOVE, SHAKE, & DROP  ", Artist = "Flo Rida ft. Pitbull" },
                new RatedTitle { Title = "Follow Me   ", Artist = "Uncle Kracker" },
                new RatedTitle { Title = "Forever ", Artist = "Chris Brown" },
                new RatedTitle { Title = "Freaks  ", Artist = "Timmy Trumpet" },
                new RatedTitle { Title = "Freaks (Extended Mix)   ", Artist = "Savage, Timmy Trumpet" },
                new RatedTitle { Title = "Funky Cold Medina   ", Artist = "Tone Loc" },
                new RatedTitle { Title = "Gangnam Style   ", Artist = "Psy" },
                new RatedTitle { Title = "Gas Pedal (Intro Edit)  ", Artist = "Sage the Gemini & IamSu" },
                new RatedTitle { Title = "GDFR    ", Artist = "Flo Rida Feat Sage The Gemini  Lookas" },
                new RatedTitle { Title = "Geronimo    ", Artist = "Sheppard" },
                new RatedTitle { Title = "Get Low ", Artist = "DJ Snake & Dillon Francis" },
                new RatedTitle { Title = "Get Low ", Artist = "Lil John And Da Eastside Boyz" },
                new RatedTitle { Title = "Get Lucky   ", Artist = "Daft Punk ft. Pharrell Williams" },
                new RatedTitle { Title = "Get Shaky   ", Artist = "Ian Carey Project" },
                new RatedTitle { Title = "Gettin\' Over You	", Artist = "David Guetta & Chris Willis Feat Fergie & Lmfao" },
                new RatedTitle { Title = "Ghetto Supastar ", Artist = "Pras Michel feat. odb and mya" },
                new RatedTitle { Title = "Ghosts \'n\' Stuff (Chuckie Remix Xmix Edit)  ", Artist = "Deadmau5 Fe. Rob Swire" },
                new RatedTitle { Title = "Girls Just Want To Have Fun (Riding In Cars With Boys)  ", Artist = "Cyndi Lauper" },
                new RatedTitle { Title = "Give me One Reason  ", Artist = "Tracy Chapman" },
                new RatedTitle { Title = "Go Girl ", Artist = "Pitbull" },
                new RatedTitle { Title = "Gold Digger (Party Break) (BPM 92)  ", Artist = "Kanye West Feat. Jamie Foxx" },
                new RatedTitle { Title = "GONNA MAKE YOU SWEAT 2016 (STARJACK BIG HORN EDIT) clean    ", Artist = "C N C MUSIC FACTORY" },
                new RatedTitle { Title = "Good Feeling    ", Artist = "Flo Rida" },
                new RatedTitle { Title = "HANGOVER 2016 (STARJACK BIG HORN EDIT)  ", Artist = "TAIO CRUZ" },
                new RatedTitle { Title = "Happy (Gru\'s Theme from Despicable Me 2)	", Artist = "Pharrell Williams" },
                new RatedTitle { Title = "HEADS WILL ROLL 2016 (STARJACK x DNK BIG HORN EDIT) clean   ", Artist = "YEAH YEAH YEAHS" },
                new RatedTitle { Title = "Hello Friday (Intro Edit)   ", Artist = "Flo Rida" },
                new RatedTitle { Title = "Here come the Hotstepper    ", Artist = "Ini Kamoze" },
                new RatedTitle { Title = "Heroes (we could be) [Feat. Tove Lo]    ", Artist = "Alesso" },
                new RatedTitle { Title = "Hey Brother ", Artist = "Avicii" },
                new RatedTitle { Title = "Hey Hey Hey (Pop Another Bottle) [djmebbe.com]  ", Artist = "Laurent Wery ft. Swiftkid & Dev" },
                new RatedTitle { Title = "Hey Ya! ", Artist = "Outkast" },
                new RatedTitle { Title = "Hip Hop Hooray (100)    ", Artist = "Naughty By Nature" },
                new RatedTitle { Title = "Hip Hop Police  ", Artist = "Chamillionaire" },
                new RatedTitle { Title = "Holiday ", Artist = "Naughty by Nature" },
                new RatedTitle { Title = "Hot in Herre    ", Artist = "Nelly" },
                new RatedTitle { Title = "Hot N Cold  ", Artist = "Katy Perry" },
                new RatedTitle { Title = "Hotel Room Service  ", Artist = "Pitbull" },
                new RatedTitle { Title = "How Bizarre ", Artist = "OMC" },
                new RatedTitle { Title = "How Deep Is Your Love   ", Artist = "Calvin Harris & Disciples" },
                new RatedTitle { Title = "How Low (138 Bpm)   ", Artist = "Ludacris" },
                new RatedTitle { Title = "How Low Can You Go (Dirty)  ", Artist = "Ludacris ft Shawnna" },
                new RatedTitle { Title = "HULA HOOP (STARJACK HYPE TRIBAL RE-DRUM) clean  ", Artist = "OMI" },
                new RatedTitle { Title = "I Don\'t Fuck With You	", Artist = "Big Sean" },
                new RatedTitle { Title = "I Don\'t Like It, I Love It (Feat. Robin Thicke, Verdine White)	", Artist = "Flo Rida" },
                new RatedTitle { Title = "I Don\'t Like It, I Love It (Feat.Robin Thicke & Verdine White)	", Artist = "Flo Rida" },
                new RatedTitle { Title = "I Got U ( Feat. Jax Jones ) ", Artist = "Duke Dumont & Jax Jones" },
                new RatedTitle { Title = "I Gotta Feeling ", Artist = "Black Eyed Peas" },
                new RatedTitle { Title = "I Like To Move It   ", Artist = "Reel 2 Real" },
                new RatedTitle { Title = "I Love It   ", Artist = "Icona Pop Feat Charli XCX" },
                new RatedTitle { Title = "I Love It   ", Artist = "Sneaky Sound System" },
                new RatedTitle { Title = "I see you Baby (feat. Gram\'ma Funk)	", Artist = "Groove Armada" },
                new RatedTitle { Title = "I Took A Pill In Ibiza (SeeB Remix) (Clean) ", Artist = "Mike Posner" },
                new RatedTitle { Title = "I Want You To Know  ", Artist = "Zedd ft Selena Gomez" },
                new RatedTitle { Title = "I\'m an Albatraoz	", Artist = "AronChupa" },
                new RatedTitle { Title = "I\'m Gonna Be (500 Miles)	", Artist = "Proclaimers" },
                new RatedTitle { Title = "Ice Ice Baby    ", Artist = "Vanilla Ice" },
                new RatedTitle { Title = "Ignition (Remix) - STR8CUT-1.0 (CLN - 134 BPM - B4-G# MAJ)	", Artist = "R Kelly" },
                new RatedTitle { Title = "In da Club  ", Artist = "50 Cent" },
                new RatedTitle { Title = "In The Ayer ", Artist = "Flo Rida" },
                new RatedTitle { Title = "Infinity (Commercial Radio Edit)    ", Artist = "The Guru Josh Project" },
                new RatedTitle { Title = "Informer    ", Artist = "Snow" },
                new RatedTitle { Title = "It Wasnt Me (XMiX Remix)   (95 BPM) ", Artist = "Shaggy" },
                new RatedTitle { Title = "It\'s Like That	", Artist = "Run DMC feat. Jason Nevins" },
                new RatedTitle { Title = "It\'s Tricky	", Artist = "Run D.M.C. vs Jason Nevins" },
                new RatedTitle { Title = "Jump (Jackson INtro Edit) (BB EDIT) ", Artist = "Kris Kross" },
                new RatedTitle { Title = "Jump Around ", Artist = "House of Pain" },
                new RatedTitle { Title = "Jungle Boogie (Ultimix) ", Artist = "Kool & The Gang" },
                new RatedTitle { Title = "Just A Dream    ", Artist = "Nelly" },
                new RatedTitle { Title = "Just Dance (feat. Colby O\'Donis)	", Artist = "Lady GaGa" },
                new RatedTitle { Title = "Just Like Fire (Ultimix by Stacy Mier)  ", Artist = "P!NK" },
                new RatedTitle { Title = "Just The Way You Are    ", Artist = "Bruno Mars" },
                new RatedTitle { Title = "Krazy   ", Artist = "Pitbull & Lil Jon" },
                new RatedTitle { Title = "Lady Marmalade  ", Artist = "Christina Aguilera, Mya, Pink, Lil Kim" },
                new RatedTitle { Title = "Last Friday Night (T.G.I.F.)    ", Artist = "Katy Perry" },
                new RatedTitle { Title = "Lean On ", Artist = "Major Lazer Feat MØ & DJ Snake" },
                new RatedTitle { Title = "Let me Blow Ya Mind (feat. Gwen Stefani)    ", Artist = "Eve" },
                new RatedTitle { Title = "Let\'s get Married	", Artist = "Jagged Edge" },
                new RatedTitle { Title = "Let\'s Get Ridiculous (Funkymix By Beat Thrillerz)	", Artist = "Redfoo" },
                new RatedTitle { Title = "Let\'s Groove	", Artist = "CDB" },
                new RatedTitle { Title = "Levels (ID) (MADEin82 Remix)    ", Artist = "Avicii" },
                new RatedTitle { Title = "Light It Up (Feat. NYLA & Fuse ODG)[Remix]  ", Artist = "Major Lazer" },
                new RatedTitle { Title = "Like A G6  (DJ Jenil Everyday I\'m Shufflin\' Intro)  ", Artist = "Far East Movement ft. The Cataracs" },
                new RatedTitle { Title = "Lips Are Movin  ", Artist = "Meghan Trainor" },
                new RatedTitle { Title = "Love Me Again (A&G Remix)   ", Artist = "John Newman" },
                new RatedTitle { Title = "Love Yourself (Jump Smokers Extended Mix)   ", Artist = "Justin Bieber" },
                new RatedTitle { Title = "Low ", Artist = "Flo Rida; T - Pain" },
                new RatedTitle { Title = "Lush Life (French Braids Mix)	", Artist = "Zara Larsson Feat.Tine Tempah" },
                new RatedTitle { Title = "Mambo No. 5(A Little Bit Of...)    ", Artist = "Lou Bega" },
                new RatedTitle { Title = "Martin Garrix   ", Artist = "Animals" },
                new RatedTitle { Title = "Memories    ", Artist = "David Guetta Feat Kid Cudi" },
                new RatedTitle { Title = "Mesmerize(feat.Ashanti)   ", Artist = "Ja Rule" },
                new RatedTitle { Title = "Miami 2 Ibiza   ", Artist = "Swedish House Mafia Vs Tinie Tempah" },
                new RatedTitle { Title = "Milkshake   ", Artist = "Kelis" },
                new RatedTitle { Title = "Morning After Dark  ", Artist = "Timbaland Feat Nelly Furtado &Soshy" },
                new RatedTitle { Title = "Moves Like Jagger   ", Artist = "Maroon 5 Feat Christina Aguilera" },
                new RatedTitle { Title = "Mr.Saxobeat    ", Artist = "Alexandra Stan" },
                new RatedTitle { Title = "My House (Dj Hope Clapapella Intro)	", Artist = "Flo Rida" },
                new RatedTitle { Title = "My Love ", Artist = "Route 94 ft.Jess Glynne" },
                new RatedTitle { Title = "My Sharona  ", Artist = "The Knack" },
                new RatedTitle { Title = "Mysterious Girl ", Artist = "Peter Andre" },
                new RatedTitle { Title = "Never Be Like You (SE)(Phase Edit)	", Artist = "Flume ft Kai" },
                new RatedTitle { Title = "New Thang   ", Artist = "Redfoo" },
                new RatedTitle { Title = "Niggas In Paris(Dj Stylezz & Dj Kirillick Remix)   ", Artist = "Jay Z ft.Kanye West" },
                new RatedTitle { Title = "No Diggity -STR8CUT - 1.0(DTY - 94 BPM - A11 - F# MIN)	", Artist = "Blackstreet(ft Dr Dre, Queen Pen)" },
                new RatedTitle { Title = "Omg ", Artist = "Usher Feat Will I Am" },
                new RatedTitle { Title = "One Dance(XMiX Remix)  ", Artist = "Drake Ft WizKid & Kyla" },
                new RatedTitle { Title = "Outside(Feat.Ellie Goulding)  ", Artist = "Calvin Harris" },
                new RatedTitle { Title = "Outside(Hardwell Remix)    ", Artist = "Calvin Harris feat.Ellie Goulding" },
                new RatedTitle { Title = "Outside(Xmix Edit) ", Artist = "Calvin Harris Fe.Ellie Goulding" },
                new RatedTitle { Title = "Paper Planes    ", Artist = "M.I.A." },
                new RatedTitle { Title = "Papercuts(feat.Vera Blue) ", Artist = "Illy" },
                new RatedTitle { Title = "Party in the U.S.A. ", Artist = "Miley Cyrus" },
                new RatedTitle { Title = "Party Rock Anthem   ", Artist = "LMFAO Feat Lauren Bennett & Goonrock" },
                new RatedTitle { Title = "Party Up(Up in Here)   ", Artist = "DMX" },
                new RatedTitle { Title = "Pass That Dutch(KANDY Bootleg) ", Artist = "Missy Elliott" },
                new RatedTitle { Title = "Peanut Butter Jelly ", Artist = "Galantis" },
                new RatedTitle { Title = "People Everyday(MMP Intro)(Clean) ", Artist = "Arrested developement" },
                new RatedTitle { Title = "Pony    ", Artist = "Ginuwine" },
                new RatedTitle { Title = "Post To Be  ", Artist = "Omarion feat Chris Brown & Jhene Aiko" },
                new RatedTitle { Title = "Pound The Alarm ", Artist = "Nicki Minaj" },
                new RatedTitle { Title = "Prayer In C ", Artist = "Lilly Wood & The Prick and Robin Schulz" },
                new RatedTitle { Title = "Price Tag   ", Artist = "Jessie J Feat B.o.B" },
                new RatedTitle { Title = "Problem ", Artist = "Ariana Grande" },
                new RatedTitle { Title = "Pump Up the Jam ", Artist = "Technotronic" },
                new RatedTitle { Title = "Push It ", Artist = "Salt \'n\' Pepa" },
                new RatedTitle { Title = "Put your Hands Up for Detroit(Radio Edit)  ", Artist = "Fedde Le Grand" },
                new RatedTitle { Title = "Pyramids(Jenil 100K Bootleg)   ", Artist = "DVBBS & Dropgun feat.Sanjin" },
                new RatedTitle { Title = "Raise Your Glass    ", Artist = "Pink" },
                new RatedTitle { Title = "Rather Be(Xmix Edit)(121 Bpm) ", Artist = "Clean Bandit Fe.Jess Glynne" },
                new RatedTitle { Title = "Real Love   ", Artist = "Jess Glynne & Clean Bandit" },
                new RatedTitle { Title = "Return Of The Mack(Autolaser Remix)[djmebbe.com]  ", Artist = "Mark Morrison" },
                new RatedTitle { Title = "Rhythm is a Dancer  ", Artist = "Snap" },
                new RatedTitle { Title = "Ride wit Me ", Artist = "Nelly" },
                new RatedTitle { Title = "Right Round Ft.Kesha   ", Artist = "Flo Rida" },
                new RatedTitle { Title = "Right Thurr - PARTYUP - 1.0 DTY(DTY - 92 BPM - A7 - D MIN) ", Artist = "Chingy" },
                new RatedTitle { Title = "Right Type of Mood  ", Artist = "Herbie" },
                new RatedTitle { Title = "Roar    ", Artist = "Katy Perry" },
                new RatedTitle { Title = "Rock This Party ", Artist = "Bob Sinclar" },
                new RatedTitle { Title = "Rock your Body  ", Artist = "Justin Timberlake" },
                new RatedTitle { Title = "Roses(Joe Maz VIP Rmx)(Phase Edit)    ", Artist = "Chainsmokers" },
                new RatedTitle { Title = "Run The World(Girls)   ", Artist = "Beyonce" },
                new RatedTitle { Title = "Runaway(U & I) ", Artist = "Galantis" },
                new RatedTitle { Title = "S & M Right Now(DJ Reenat Mashup)    ", Artist = "Rihanna" },
                new RatedTitle { Title = "Satisfaction    ", Artist = "Benny Benassi" },
                new RatedTitle { Title = "Scatman(SE)[VM EDIT]  ", Artist = "Scatman John" },
                new RatedTitle { Title = "Scream & Shout(feat.Britney Spears)   ", Artist = "Will.I.Am" },
                new RatedTitle { Title = "Seek Bromance   ", Artist = "Tim Berg" },
                new RatedTitle { Title = "Sexual Healing  ", Artist = "Max A Million" },
                new RatedTitle { Title = "Sexy And I Know It  ", Artist = "LMFAO" },
                new RatedTitle { Title = "Sexy Bitch(feat.Akon) ", Artist = "David Guetta" },
                new RatedTitle { Title = "Sexy Love   ", Artist = "Ne - Yo" },
                new RatedTitle { Title = "Sexyback    ", Artist = "Justin Timberlake" },
                new RatedTitle { Title = "Shackles(Praise You)   ", Artist = "Mary Mary" },
                new RatedTitle { Title = "Shake It Off    ", Artist = "Taylor Swift" },
                new RatedTitle { Title = "Shake That  ", Artist = "Eminem feat Nate Dogg" },
                new RatedTitle { Title = "Shook Me All Night(CFLO Edit)  ", Artist = "ACDC" },
                new RatedTitle { Title = "Shots   ", Artist = "LMFAO feat.Lil Jon" },
                new RatedTitle { Title = "Shut It Down    ", Artist = "Pitbull Feat Akon" },
                new RatedTitle { Title = "Shut Up and Dance   ", Artist = "Walk The Moon" },
                new RatedTitle { Title = "Sing Hallelujah ", Artist = "Dr Alban" },
                new RatedTitle { Title = "Single Ladies(Put a Ring on It)    ", Artist = "Beyonce" },
                new RatedTitle { Title = "Slice of Heaven ", Artist = "Dave Dobbyn & Herbs" },
                new RatedTitle { Title = "Smells Like Teen Spirit(CFLO Intro)    ", Artist = "Nirvana" },
                new RatedTitle { Title = "Smooth Criminal(N2N Remix)(Enrie BeeHive Edit)    ", Artist = "Michael Jackson" },
                new RatedTitle { Title = "So What ", Artist = "Pink" },
                new RatedTitle { Title = "Somebody    ", Artist = "Natalie La Rose feat.Jeremih" },
                new RatedTitle { Title = "Sorry(Natasha Baccardi & Dmitriy Rs Remix) ", Artist = "Justin Bieber" },
                new RatedTitle { Title = "Starships(Explicit Edit)   ", Artist = "Nicki Minaj" },
                new RatedTitle { Title = "Stay the Night(feat.Hayley Williams of Paramore)  ", Artist = "Zedd" },
                new RatedTitle { Title = "Still D.R.E ", Artist = "Dr Dre & Snoop Dogg" },
                new RatedTitle { Title = "Still D.R.E. (feat Snoop Dogg)  ", Artist = "Dr.Dre" },
                new RatedTitle { Title = "Stolen Dance    ", Artist = "Milky Chance" },
                new RatedTitle { Title = "Stressed Out(Dave Winnel Remix X - Mix Edit) ", Artist = "Twenty One Pilots" },
                new RatedTitle { Title = "Stronger    ", Artist = "Kanye West" },
                new RatedTitle { Title = "Sugar   ", Artist = "Maroon 5" },
                new RatedTitle { Title = "Sugar(130 Bpm) ", Artist = "Flo - Rida Ft Wynter" },
                new RatedTitle { Title = "Sugar Man   ", Artist = "Yolanda Be Cool & Dcup" },
                new RatedTitle { Title = "Summer(Radio Edit) ", Artist = "Calvin Harris" },
                new RatedTitle { Title = "Summer Love - PARTYUP - 1.0 DTY(DTY - 96 BPM - A4 - F MIN) ", Artist = "Justin Timberlake" },
                new RatedTitle { Title = "Summer of \'69	", Artist = "Bryan Adams" },
                new RatedTitle { Title = "Summertime Sadness(Remix)  ", Artist = "Lana Del Rey Vs Cedric Gervais" },
                new RatedTitle { Title = "Sweet Dreams(Extended) ", Artist = "Eurythmics" },
                new RatedTitle { Title = "Sweet Home Alabama  ", Artist = "Lynyrd Skynyrd" },
                new RatedTitle { Title = "Sweet Lovin\' (Steve Smart Remix)	", Artist = "Sigala" },
                new RatedTitle { Title = "Sweet Nothing   ", Artist = "Calvin Harris Feat Florence Welch" },
                new RatedTitle { Title = "Swing   ", Artist = "Savage" },
                new RatedTitle { Title = "Swing(Original Mix)    ", Artist = "Joel Fletcher & Savage" },
                new RatedTitle { Title = "T.N.T.  ", Artist = "ACDC" },
                new RatedTitle { Title = "Take Over Control(DJ Pitchugin Bootleg)    ", Artist = "Afrojack ft Eva Simons, Spencer & Hill" },
                new RatedTitle { Title = "Take You There(REEO Mix)[115 BPM] ", Artist = "Sean Kingston" },
                new RatedTitle { Title = "Talk Dirty(feat. 2 Chainz) ", Artist = "Jason Derulo" },
                new RatedTitle { Title = "Talkin\' Bout A Revolution (Bobby Brush & Deep Chills Remix)	", Artist = "Tracy Chapman" },
                new RatedTitle { Title = "Temperature ", Artist = "Sean Paul" },
                new RatedTitle { Title = "Temperature(Bonus)(XMiX Remix)    ", Artist = "Sean Paul" },
                new RatedTitle { Title = "The Days    ", Artist = "Avicii" },
                new RatedTitle { Title = "The Edge Of Glory   ", Artist = "Lady Gaga" },
                new RatedTitle { Title = "The Fix ", Artist = "Nelly Feat.Jeremih" },
                new RatedTitle { Title = "The Horses  ", Artist = "Daryl Braithwaite" },
                new RatedTitle { Title = "The Logical Song    ", Artist = "Scooter" },
                new RatedTitle { Title = "The Nights(Extended Mix)   ", Artist = "Avicii" },
                new RatedTitle { Title = "The Time(Dirty Bit)    ", Artist = "The Black Eyed Peas" },
                new RatedTitle { Title = "The Time(The Dirty Bit)(The Time For Reals Edit)[DJ Mebbe]   ", Artist = "Black Eyed Peas" },
                new RatedTitle { Title = "The Way I Are   ", Artist = "Timbaland" },
                new RatedTitle { Title = "The Way You Make Me Feel    ", Artist = "Michael Jackson" },
                new RatedTitle { Title = "The Way you Move(feat.Sleepy Brown)   ", Artist = "Outkast" },
                new RatedTitle { Title = "Thing   ", Artist = "Amerie" },
                new RatedTitle { Title = "Thinking Out Loud   ", Artist = "Ed Sheeran" },
                new RatedTitle { Title = "This Is How We Do It(Aca In)(SE)(Marty Mar Edit) ", Artist = "Montell Jordan" },
                new RatedTitle { Title = "This Is What You Came For(100 - 124 Transition)(Kutt Edit)  ", Artist = "Calvin Harris & Rihanna" },
                new RatedTitle { Title = "Thong Song  ", Artist = "Sisqo" },
                new RatedTitle { Title = "Thrift Shop(feat.Wanz)    ", Artist = "Macklemore & Ryan Lewis" },
                new RatedTitle { Title = "Thriller    ", Artist = "Michael Jackson" },
                new RatedTitle { Title = "Throw Your Hands Up ", Artist = "Qwote Ft.Pitbull & Lucenzo" },
                new RatedTitle { Title = "Thunderstruck   ", Artist = "AC DC" },
                new RatedTitle { Title = "Thunderstruck   ", Artist = "ACDC" },
                new RatedTitle { Title = "Tik Tok ", Artist = "Ke$ha" },
                new RatedTitle { Title = "Timber  ", Artist = "Pitbull" },
                new RatedTitle { Title = "Time of Our Lives   ", Artist = "Pitbull" },
                new RatedTitle { Title = "Titanium    ", Artist = "David Guetta Feat Sia" },
                new RatedTitle { Title = "Tonight Is the Night    ", Artist = "Outasight" },
                new RatedTitle { Title = "Trumpets    ", Artist = "Jason Derulo" },
                new RatedTitle { Title = "Tsunami(Original Mix)  ", Artist = "DVBBS & Borgeous" },
                new RatedTitle { Title = "Turn All The Lights On Mix by Stacy Mier    ", Artist = "T - Pain f.Ne - Yo" },
                new RatedTitle { Title = "Turn Down For What  ", Artist = "DJ Snake & Lil John" },
                new RatedTitle { Title = "Turn Me On  ", Artist = "David Guetta Ft.Nicki Minaj" },
                new RatedTitle { Title = "Turn Up The Music   ", Artist = "Chris Brown" },
                new RatedTitle { Title = "U Can\'t Touch This	", Artist = "MC Hammer" },
                new RatedTitle { Title = "Uptown Funk ", Artist = "Mark Ronson" },
                new RatedTitle { Title = "Wake Me Up  ", Artist = "Avicii" },
                new RatedTitle { Title = "Walk This Way   ", Artist = "Run - DMC Feat.Aerosmith" },
                new RatedTitle { Title = "Wall To Wall    ", Artist = "  Chris Brown" },
                new RatedTitle { Title = "Wanna Be Startin\' Somethin\'(Alternate Ending)(122 Bpm) ", Artist = "  Michael Jackson" },
                new RatedTitle { Title = "Wannabe ", Artist = "  Spice Girls" },
                new RatedTitle { Title = "Watch Me    ", Artist = "  Silento" },
                new RatedTitle { Title = "Waves(Robin Schulz Remix)  ", Artist = "Mr.Probz, Robin Schulz" },
                new RatedTitle { Title = "We Found Love   ", Artist = "Rihanna Feat Calvin Harris" },
                new RatedTitle { Title = "We Will Rock You    ", Artist = "Queen" },
                new RatedTitle { Title = "When Love Takes Over(feat.Kelly Rowland)  ", Artist = "David Guetta" },
                new RatedTitle { Title = "Where Have You Been[djmebbe.com]   ", Artist = "Rihanna" },
                new RatedTitle { Title = "Where\'s your Head At	", Artist = "Basement Jaxx" },
                new RatedTitle { Title = "Whip It!(feat.Chloe Angelides)", Artist = "LunchMoney Lewis" },
                new RatedTitle { Title = "Whistle ", Artist = "Flo Rida" },
                new RatedTitle { Title = "White Noise (Hotel Garuda Edition)	", Artist = "Disclosure" },
                new RatedTitle { Title = "Who Let the Dogs Out    ", Artist = "Baha Men" },
                new RatedTitle { Title = "Whomp(There It Is) ", Artist = "Tag Team" },
                new RatedTitle { Title = "Wiggle(feat.Snoop Dogg)   ", Artist = "Jason Derulo" },
                new RatedTitle { Title = "Wild Ones   ", Artist = "Flo Rida Feat Sia" },
                new RatedTitle { Title = "Wild Thing  ", Artist = "Tone Loc" },
                new RatedTitle { Title = "Wild Wild Love(feat.G.R.L.)   ", Artist = "Pitbull" },
                new RatedTitle { Title = "Without Me (Olly James Festival Bootleg) (2016) ", Artist = "Eminem" },
                new RatedTitle { Title = "WITHOUT ME (STARJACK x OLLY JAMES BIG ROOM HITTER) clean    ", Artist = "EMINEM x GARMIANI" },
                new RatedTitle { Title = "Wonderwall  ", Artist = "Oasis" },
                new RatedTitle { Title = "Work From Home(No Rap Edit)    ", Artist = "Fifth Harmony" },
                new RatedTitle { Title = "Work It ", Artist = "Missy Elliot" },
                new RatedTitle { Title = "Work It Out(ft.Dave Matthews Band)    ", Artist = "Jurassic 5" },
                new RatedTitle { Title = "Worth It (Feat.Kid Ink)	", Artist = "Fifth Harmony" },
                new RatedTitle { Title = "Yeah 3X(Explicit Edit) ", Artist = "Chris Brown" },
                new RatedTitle { Title = "Yeah!(feat.Lil Jon & Ludacris)	", Artist = "Usher" },
                new RatedTitle { Title = "You ain\'t Thinking (About Me)	", Artist = "Sonia Dada" },
                new RatedTitle { Title = "You Know You Like It    ", Artist = "DJ Snake &AlunaGeorge" },
                new RatedTitle { Title = "You Shook Me All Night Long ", Artist = "AC / DC" }
            };

            for (int i = 0; i < _ratedTitles.Count; i++)
            {
                IRatedTitle ratedTitle = new RatedTitle();
                ratedTitle = _ratedTitles[i];

                ratedTitle = RemoveFeaturingArtists(ratedTitle, "&");
                ratedTitle = RemoveFeaturingArtists(ratedTitle, ",");
                ratedTitle = RemoveFeaturingArtists(ratedTitle, "(");
                ratedTitle = RemoveFeaturingArtists(ratedTitle, "[");
                ratedTitle = RemoveFeaturingArtists(ratedTitle, "-");
                ratedTitle = RemoveFeaturingArtists(ratedTitle, "Featuring");
                ratedTitle = RemoveFeaturingArtists(ratedTitle, "Feat.");
                ratedTitle = RemoveFeaturingArtists(ratedTitle, "Feat ");
                ratedTitle = RemoveFeaturingArtists(ratedTitle, "Ft.");
                ratedTitle = RemoveFeaturingArtists(ratedTitle, "Ft ");
                ratedTitle = RemoveFeaturingArtists(ratedTitle, "Fe.");
                ratedTitle = RemoveFeaturingArtists(ratedTitle, "F ");

                ratedTitle.Artist.Trim();
                ratedTitle.Title.Trim();
            }

            return _ratedTitles;
        }

        private IRatedTitle RemoveFeaturingArtists(IRatedTitle ratedTitle, string extra)
        {
            var index = ratedTitle.Artist.IndexOf(extra, StringComparison.OrdinalIgnoreCase);

            if (index > 0)
                ratedTitle.Artist = ratedTitle.Artist.Substring(0, index - 1);


            index = ratedTitle.Title.IndexOf(extra, StringComparison.OrdinalIgnoreCase);

            if (index > 0)
                ratedTitle.Title = ratedTitle.Title.Substring(0, index - 1);

            return ratedTitle;
        }

        public bool IsRatedTitle(string artist, string title)
        {
            var isRatedTitle = false;

            foreach (var ratedTitle in _ratedTitles)
            {
                if (artist.IndexOf(ratedTitle.Artist, StringComparison.OrdinalIgnoreCase) >= 0
                    && title.IndexOf(ratedTitle.Title, StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    isRatedTitle = true;
                    break;
                }
            }

            return isRatedTitle;
        }
    }
}
