using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Ratings
{
    public class RatedArtists : IRatedArtists
    {
        List<IRatedArtist> _ratedArtists;

        public List<IRatedArtist> GetRatedArtists()
        {
            _ratedArtists = new List<IRatedArtist>
            {
                new RatedArtist { Artist = "50 Cent" },
                new RatedArtist { Artist = "Abba" },
                new RatedArtist { Artist = "AC DC" },
                new RatedArtist { Artist = "AC/DC" },
                new RatedArtist { Artist = "ACDC" },
                new RatedArtist { Artist = "Afrojack" },
                new RatedArtist { Artist = "Akon" },
                new RatedArtist { Artist = "Ariana Grande" },
                new RatedArtist { Artist = "Armand Van Helden" },
                new RatedArtist { Artist = "Avicii" },
                new RatedArtist { Artist = "Axwell" },
                new RatedArtist { Artist = "B.o.B" },
                new RatedArtist { Artist = "Benni Benassi" },
                new RatedArtist { Artist = "Beyonce" },
                new RatedArtist { Artist = "Beyoncé" },
                new RatedArtist { Artist = "Bingo Players" },
                new RatedArtist { Artist = "Black Eyed Peas" },
                new RatedArtist { Artist = "Bob Sinclar" },
                new RatedArtist { Artist = "Bombs Away" },
                new RatedArtist { Artist = "Bon Jovi" },
                new RatedArtist { Artist = "Britney Spears" },
                new RatedArtist { Artist = "Bruno Mars" },
                new RatedArtist { Artist = "C & C Music Factory" },
                new RatedArtist { Artist = "C N C MUSIC FACTORY" },
                new RatedArtist { Artist = "Calvin Harris" },
                new RatedArtist { Artist = "Chainsmokers" },
                new RatedArtist { Artist = "Charli X C X" },
                new RatedArtist { Artist = "Charli XCX" },
                new RatedArtist { Artist = "Chingy" },
                new RatedArtist { Artist = "Chris Brown" },
                new RatedArtist { Artist = "Ciara" },
                new RatedArtist { Artist = "Clean Bandit" },
                new RatedArtist { Artist = "Cookin ON 3 Burners" },
                new RatedArtist { Artist = "Coolio" },
                new RatedArtist { Artist = "Cypress Hill" },
                new RatedArtist { Artist = "D-12" },
                new RatedArtist { Artist = "D.Guetta" },
                new RatedArtist { Artist = "D12" },
                new RatedArtist { Artist = "Daft Punk" },
                new RatedArtist { Artist = "David Guetta" },
                new RatedArtist { Artist = "Deadmau5" },
                new RatedArtist { Artist = "Destiny Child" },
                new RatedArtist { Artist = "Destiny's Child" },
                new RatedArtist { Artist = "Destinys Child" },
                new RatedArtist { Artist = "Disclosure" },
                new RatedArtist { Artist = "Dizzee Rascal" },
                new RatedArtist { Artist = "DJ Jenil" },
                new RatedArtist { Artist = "DJ Snake" },
                new RatedArtist { Artist = "DMX" },
                new RatedArtist { Artist = "Dr Dre" },
                new RatedArtist { Artist = "Dr. Dre" },
                new RatedArtist { Artist = "Dr.Dre" },
                new RatedArtist { Artist = "Drake" },
                new RatedArtist { Artist = "Eminem" },
                new RatedArtist { Artist = "Enrique Iglesias" },
                new RatedArtist { Artist = "Eric Prydz" },
                new RatedArtist { Artist = "Eve" },
                new RatedArtist { Artist = "Far East Movement" },
                new RatedArtist { Artist = "Fatman Scoop" },
                new RatedArtist { Artist = "Fedde Le Grand" },
                new RatedArtist { Artist = "Fergie" },
                new RatedArtist { Artist = "Fetty Wap" },
                new RatedArtist { Artist = "Fifth Harmony" },
                new RatedArtist { Artist = "Flo Rida" },
                new RatedArtist { Artist = "Flo-Rida" },
                new RatedArtist { Artist = "G.R.L" },
                new RatedArtist { Artist = "Galantis" },
                new RatedArtist { Artist = "Game, The" },
                new RatedArtist { Artist = "Gym Class Heroes" },
                new RatedArtist { Artist = "Hardwell" },
                new RatedArtist { Artist = "Havana Brown" },
                new RatedArtist { Artist = "Hilltop Hoods" },
                new RatedArtist { Artist = "Hook N Sling" },
                new RatedArtist { Artist = "House of Pain" },
                new RatedArtist { Artist = "Ice Cube" },
                new RatedArtist { Artist = "Icona Pop" },
                new RatedArtist { Artist = "Iggy Azalea" },
                new RatedArtist { Artist = "Illy" },
                new RatedArtist { Artist = "J-Lo" },
                new RatedArtist { Artist = "Ja Rule" },
                new RatedArtist { Artist = "Jackson 5" },
                new RatedArtist { Artist = "Jagged Edge" },
                new RatedArtist { Artist = "Jason Derulo" },
                new RatedArtist { Artist = "Jay Sean" },
                new RatedArtist { Artist = "Jay Z" },
                new RatedArtist { Artist = "Jay-Z" },
                new RatedArtist { Artist = "Jenil" },
                new RatedArtist { Artist = "Jennifer Lopez" },
                new RatedArtist { Artist = "Jeremih" },
                new RatedArtist { Artist = "Jess Glynne" },
                new RatedArtist { Artist = "Jessica Mauboy" },
                new RatedArtist { Artist = "Jessie J" },
                new RatedArtist { Artist = "John Newman" },
                new RatedArtist { Artist = "Jon Bon Jovi" },
                new RatedArtist { Artist = "Justice Crew" },
                new RatedArtist { Artist = "Justin Beiber" },
                new RatedArtist { Artist = "Justin Bieber" },
                new RatedArtist { Artist = "Justin Timberlake" },
                new RatedArtist { Artist = "Kanye West" },
                new RatedArtist { Artist = "Katy Perry" },
                new RatedArtist { Artist = "Ke$ha" },
                new RatedArtist { Artist = "Kelis" },
                new RatedArtist { Artist = "Kelly Rowland" },
                new RatedArtist { Artist = "Kesha" },
                new RatedArtist { Artist = "Knife Party" },
                new RatedArtist { Artist = "Kungs & Cookin' On 3 Burners" },
                new RatedArtist { Artist = "KUNGS vs COOKIN ON 3 BURNERS" },
                new RatedArtist { Artist = "Kylie Minogue" },
                new RatedArtist { Artist = "LADY GA GA" },
                new RatedArtist { Artist = "Lady Gaga" },
                new RatedArtist { Artist = "Laidback Luke" },
                new RatedArtist { Artist = "Lana Del Dey" },
                new RatedArtist { Artist = "Lil Jon" },
                new RatedArtist { Artist = "Lil Wayne" },
                new RatedArtist { Artist = "Limp Bizkit" },
                new RatedArtist { Artist = "Little Mix" },
                new RatedArtist { Artist = "LL Cool J" },
                new RatedArtist { Artist = "LMFAO" },
                new RatedArtist { Artist = "LOO & PLACIDO" },
                new RatedArtist { Artist = "Ludacris" },
                new RatedArtist { Artist = "Lunchmoney Lewis" },
                new RatedArtist { Artist = "MACKLEMORE" },
                new RatedArtist { Artist = "Macklemore & Ryan Lewis" },
                new RatedArtist { Artist = "Madonna" },
                new RatedArtist { Artist = "Major Lazer" },
                new RatedArtist { Artist = "Maroon 5" },
                new RatedArtist { Artist = "Martin Garrix" },
                new RatedArtist { Artist = "Martin Solveig" },
                new RatedArtist { Artist = "Mary J Blige" },
                new RatedArtist { Artist = "Meghan Trainor" },
                new RatedArtist { Artist = "Michael Jackson" },
                new RatedArtist { Artist = "Micheal Jackson" },
                new RatedArtist { Artist = "Missy Elliot" },
                new RatedArtist { Artist = "Mr Probz" },
                new RatedArtist { Artist = "Mr.Probz" },
                new RatedArtist { Artist = "Naughty By Nature" },
                new RatedArtist { Artist = "Ne Yo" },
                new RatedArtist { Artist = "Ne-Yo" },
                new RatedArtist { Artist = "Nelly" },
                new RatedArtist { Artist = "Nelly Furtado" },
                new RatedArtist { Artist = "Neyo" },
                new RatedArtist { Artist = "Nicki Minaj" },
                new RatedArtist { Artist = "Nicky Romero" },
                new RatedArtist { Artist = "Nico & Vinz" },
                new RatedArtist { Artist = "Nicole scherzinger" },
                new RatedArtist { Artist = "Nirvana" },
                new RatedArtist { Artist = "Notorious B.I.G" },
                new RatedArtist { Artist = "Notorious Big" },
                new RatedArtist { Artist = "Outkast" },
                new RatedArtist { Artist = "P!nk" },
                new RatedArtist { Artist = "Peking Duk" },
                new RatedArtist { Artist = "Pharrell" },
                new RatedArtist { Artist = "Pharrell Williams" },
                new RatedArtist { Artist = "Pink" },
                new RatedArtist { Artist = "Pitbull" },
                new RatedArtist { Artist = "Potbelleez" },
                new RatedArtist { Artist = "Presets" },
                new RatedArtist { Artist = "Pussy Cat Dolls" },
                new RatedArtist { Artist = "Pussycat Dolls" },
                new RatedArtist { Artist = "Queen" },
                new RatedArtist { Artist = "R Kelly" },
                new RatedArtist { Artist = "R. Kelly" },
                new RatedArtist { Artist = "R.Kelly" },
                new RatedArtist { Artist = "R3hab" },
                new RatedArtist { Artist = "Redfoo" },
                new RatedArtist { Artist = "Reel 2 Real" },
                new RatedArtist { Artist = "Reel to Real" },
                new RatedArtist { Artist = "Rihanna" },
                new RatedArtist { Artist = "Robin Schulz" },
                new RatedArtist { Artist = "Route 94" },
                new RatedArtist { Artist = "Rudimental" },
                new RatedArtist { Artist = "Run DMC" },
                new RatedArtist { Artist = "Run-D.M.C." },
                new RatedArtist { Artist = "Run-DMC" },
                new RatedArtist { Artist = "Salt 'N Pepa" },
                new RatedArtist { Artist = "Salt 'n' Pepa" },
                new RatedArtist { Artist = "Salt and Pepa" },
                new RatedArtist { Artist = "Salt n Pepa" },
                new RatedArtist { Artist = "Salt N Pepa" },
                new RatedArtist { Artist = "Salt-N-Pepa" },
                new RatedArtist { Artist = "Savage" },
                new RatedArtist { Artist = "Sean Kingston" },
                new RatedArtist { Artist = "Sean Paul" },
                new RatedArtist { Artist = "Selena Gomez" },
                new RatedArtist { Artist = "Shaggy" },
                new RatedArtist { Artist = "Showtek" },
                new RatedArtist { Artist = "Sia" },
                new RatedArtist { Artist = "Sir Mix A-Lot" },
                new RatedArtist { Artist = "Sir Mix-a-lot" },
                new RatedArtist { Artist = "Sir Mix-a-Lot" },
                new RatedArtist { Artist = "Sir Mix-A-Lot" },
                new RatedArtist { Artist = "Skrillex" },
                new RatedArtist { Artist = "Sneaky Sound System" },
                new RatedArtist { Artist = "Snoop Dogg" },
                new RatedArtist { Artist = "Steve Angello" },
                new RatedArtist { Artist = "Steve Aoki" },
                new RatedArtist { Artist = "Swedish House Mafia" },
                new RatedArtist { Artist = "T Pain" },
                new RatedArtist { Artist = "T-Pain" },
                new RatedArtist { Artist = "T. I." },
                new RatedArtist { Artist = "T.I." },
                new RatedArtist { Artist = "Taio Cruz" },
                new RatedArtist { Artist = "Taylor Swift" },
                new RatedArtist { Artist = "The Avalanches" },
                new RatedArtist { Artist = "The Black Eyed Peas" },
                new RatedArtist { Artist = "The Chainsmokers" },
                new RatedArtist { Artist = "The Game" },
                new RatedArtist { Artist = "The Jacksons" },
                new RatedArtist { Artist = "The Notorious B.I.G" },
                new RatedArtist { Artist = "The Notorious Big" },
                new RatedArtist { Artist = "The Wanted" },
                new RatedArtist { Artist = "Tiesto" },
                new RatedArtist { Artist = "Tiësto" },
                new RatedArtist { Artist = "Timbaland" },
                new RatedArtist { Artist = "Timmy Trumpet" },
                new RatedArtist { Artist = "Timomatic" },
                new RatedArtist { Artist = "TJR" },
                new RatedArtist { Artist = "TLC" },
                new RatedArtist { Artist = "Tocadisco" },
                new RatedArtist { Artist = "Tommy Trash" },
                new RatedArtist { Artist = "Tone Loc" },
                new RatedArtist { Artist = "Tracy Chapman" },
                new RatedArtist { Artist = "Twenty one pilots" },
                new RatedArtist { Artist = "Tyga" },
                new RatedArtist { Artist = "Usher" },
                new RatedArtist { Artist = "Whitney Houston" },
                new RatedArtist { Artist = "Will Smith" },
                new RatedArtist { Artist = "Will.I.Am" },
                new RatedArtist { Artist = "WIZ KHALIFA" },
                new RatedArtist { Artist = "Wolfgang Gartner" },
                new RatedArtist { Artist = "YG" },
                new RatedArtist { Artist = "Yolanda Be Cool" },
                new RatedArtist { Artist = "Zedd" }
            };

            return _ratedArtists;
        }

        public bool IsRatedArtist(string artist)
        {
            var isRatedArtist = false;

            foreach (var ratedArtist in _ratedArtists)
            {
                if (artist.IndexOf(ratedArtist.Artist, StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    isRatedArtist = true;
                    break;
                }
            }

            return isRatedArtist;
        }
    }
}
